### ISSUE TITLE
Code for training and testing on BCSS dataset

### ISSUE THREAD

**Issue by o0t1ng0o** [cvlab-stonybrook/PLM_SSL#1]
Hi @jingweizhang-xyz ,

Thank you for sharing your code.
Could you provide the code to train and test on BCSS dataset and the pre-trained model?

Thank you in advance.

**Comment by jingweizhang-xyz** [comment]
Thank you for your comment, I am organizing the code and will share it with you soon.

**Comment by jingweizhang-xyz** [comment]
Sorry for the late update. We have updated the downstream code for the BCSS dataset.
Here is the link to our pretrained model on the TCGA-BRCA-100K dataset: https://drive.google.com/file/d/1hSmW04Yh2JSDs287jtWRqrBPOmoWyGTD/view?usp=sharing
