### ISSUE TITLE
BCSS dataset ImageFolder

### ISSUE THREAD

**Issue by shuaijun-36** [cvlab-stonybrook/PLM_SSL#5]
Thank you very much for your patience!
how do you spilt bcss training and testing dataset, and what do your imagefolders look like?

**Comment by jingweizhang-xyz** [comment]
We followed the official training and testing split as showed in https://bcsegmentation.grand-challenge.org/Baseline.
The input Imagefolder looks like:
root_dir (e.g. train)
-mask
--img_id
---img_id_x_y.png
-img
--img_id
---img_id_x_y.png

**Comment by shuaijun-36** [comment]
> We followed the official training and testing split as showed in https://bcsegmentation.grand-challenge.org/Baseline. The input Imagefolder looks like: root_dir (e.g. train) -mask --img_id ---img_id_x_y.png -img --img_id ---img_id_x_y.png

thank you>.<
