### ISSUE TITLE
TCGA-BRCA dataset

### ISSUE THREAD

**Issue by shuaijun-36** [cvlab-stonybrook/PLM_SSL#6]
where can i download the TCGA-BRCA dataset

**Comment by shuaijun-36** [comment]
why I downloaded from [https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=3539225#3539225297797a99bb444d3a9139690b0ceb31d](url) is .dcm files, and the metadata file says they are MRI images?

**Comment by shuaijun-36** [comment]
could you please provide the 'TCGA-BRCA-100K' dataset created by you? 
：）

**Comment by jingweizhang-xyz** [comment]
You can get access to TCGA-BRCA slides here: [https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-BRCA%22%5D%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%5D%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D&searchTableTab=files](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-BRCA%22%5D%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%5D%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D&searchTableTab=files) I remembered that they have a command line program and a GUI program to download it. I am packing TCGA-BRCA-100k and will share with you later.

**Comment by jingweizhang-xyz** [comment]
Here it is: [https://drive.google.com/file/d/1ii8-kzuHWsMerlVxj-xsQk0G0lzmAL-Q/view?usp=sharing](https://drive.google.com/file/d/1ii8-kzuHWsMerlVxj-xsQk0G0lzmAL-Q/view?usp=sharing)
